### ISSUE TITLE
Question: Which is the official and active repository for Quick Pad?

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [yaichenbaum/Quick-Pad#434]
Previously the repo for Quick Pad was under the UWP community organization account but now it's under your account. However when searching for Quick Pad on GitHub there's another repository called https://github.com/fredatgithub/Quick-Pad which was last updated last year. Is this the right repository for Quick Pad? Also for some reason the old issues are closed even if their are not implemented.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This is the official repository for GitHub, it's not very active anymore but it gets bug fixes every now and then.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran This is the official repository for Quick Pad, it's not very active anymore but it gets bug fixes every now and then.
