### ISSUE TITLE
Disable the splash screen

### ISSUE THREAD

**Issue by AkazaRenn** [yaichenbaum/Quick-Pad#439]
**Is your feature request related to a problem? Please describe.**

It's not an issue but something I would like to see it have. When opening the app there will be splash screen like the one below. Since the color of the icon is mostly blue, it doesn't fit the color of my system very well, especially when it is a tool I expect to replace the native notepad.
![image](https://user-images.githubusercontent.com/8340896/100308357-2f3b6480-2f76-11eb-820d-6036dacb5218.png)

**Describe the solution you'd like**

I would like to see the splash screen disabled.

**Describe alternatives you've considered**

A pseudo-UI as the splash screen.

**Comment by yaichenbaum** [comment]
@AkazaRenn The splash screen only shows while the app is loading, that shouldn't be very long if you are on the latest version. What version of the app do you have?

**Comment by AkazaRenn** [comment]
> on of the app do you have?

That's 5.0.0.0, you are right it doesn't last for a very long time but would be great if it can be changed.

**Comment by yaichenbaum** [comment]
> > on of the app do you have?
> 
> That's 5.0.0.0, you are right it doesn't last for a very long time but would be great if it can be changed.

There isn't any other way to configure this.

**Comment by AkazaRenn** [comment]
> > > on of the app do you have?
> > 
> > 
> > That's 5.0.0.0, you are right it doesn't last for a very long time but would be great if it can be changed.
> 
> There isn't any other way to configure this.

https://stackoverflow.com/questions/47201701/removing-splash-screen-from-uwp-app-in-fall-creators-update-fcu

I think it worth a try

**Comment by yaichenbaum** [comment]
@AkazaRenn Quick Pad already uses that in addition to some other optimizations, however a splash screen will still display for a little bit depending on how powerful your device is and what else is open at the time.
