### ISSUE TITLE
New file icon

### ISSUE THREAD

**Issue by AkazaRenn** [yaichenbaum/Quick-Pad#440]
**Is your feature request related to a problem? Please describe.**

Feature request, I would like a new icon for the files associated. But I'm not sure if the current one is there by design, feel free to close the issue if that's the case.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/8340896/100309110-12a02c00-2f78-11eb-9589-8e03da4efc36.png)
Take a reference from the PDF icon made by Microsoft for a better "feel of integration" into the system.

**Describe alternatives you've considered**

The icons used by Notepads (https://github.com/mah-qurashy/Notepads-Icon), they are pretty well designed.

**Comment by yaichenbaum** [comment]
@AkazaRenn The current icons were designed for Quick Pad, we don't have one for PDF files because Quick Pad doesn't support PDF files.

**Comment by AkazaRenn** [comment]
> @AkazaRenn The current icons were designed for Quick Pad, we don't have one for PDF files because Quick Pad doesn't support PDF files.

No problem. I thought the file icon was designed with the old icon of the app, since the app icon has been updated so should the file icon. Never mind.
