### ISSUE TITLE
Release Package?

### ISSUE THREAD

**Issue by rashil2000** [yaichenbaum/Quick-Pad#441]
The releases page only contains the source code. I'm trying to make a Scoop manifest for Quick-Pad. How do I get the release package (exe or msixbundle)?

**Comment by yaichenbaum** [comment]
@rashil2000 You would need to compile Quick Pad from the source code for that, the reason I don't provide an msixbundle is because it will need a valid certificate for someone else to install it.

**Comment by rashil2000** [comment]
@yaichenbaum If it needs to recompile every time, then scoop can't install it. Scoop is just a downloader-extracter.

**Comment by yaichenbaum** [comment]
> @yaichenbaum If it needs to recompile every time, then scoop can't install it. Scoop is just a downloader-extracter.

I meant you would need to compile it to create the package and add your own certificate.

**Comment by rashil2000** [comment]
I was wondering how different this process is for installing other apps, like Files - Preview for example. How does it handle certificates?

**Comment by yaichenbaum** [comment]
> I was wondering how different this process is for installing other apps, like Files - Preview for example. How does it handle certificates?

Files uses the package from the Store, however, the store version of Quick Pad has a charge so I cannot use the same package here.

**Comment by rashil2000** [comment]
@yaichenbaum Oh was it made paid recently? I have the Store-installed version but I don't think I paid for it.

Anyway, thanks for the info!

**Comment by AqilCont** [comment]
Ah, so we have to build it ourselves? Wouldn't it be a lot more accessible if you somehow provided prebuilt bundles if you're making it open source anyways, even without certificates? It's an awful lot of trouble for me to compile this, so just gave a suggestion. xd

**Comment by yaichenbaum** [comment]
> Ah, so we have to build it ourselves? Wouldn't it be a lot more accessible if you somehow provided prebuilt bundles if you're making it open source anyways, even without certificates? It's an awful lot of trouble for me to compile this, so just gave a suggestion. xd

Prebuilt packages cannot be installed without a certificate.

**Comment by AqilCont** [comment]
I don't have much experience, but can't we install anything with Dev Mode on Win10? We have to turn it on anyways to build it(if you are using VS). I'm getting a few errors while building(this is my first time building/dealing with anything UWP) so I was curious if the original dev, who can obv do it much better than me, can just provide the binaries for the app.

**Comment by yaichenbaum** [comment]
> I don't have much experience, but can't we install anything with Dev Mode on Win10? We have to turn it on anyways to build it(if you are using VS). I'm getting a few errors while building(this is my first time building/dealing with anything UWP) so I was curious if the original dev, who can obv do it much better than me, can just provide the binaries for the app.

Dev mode still requires packages to have a certificate.

**Comment by AqilCont** [comment]
Ah, rip. Oh well. Sorry again!
