### ISSUE TITLE
[Feature] Ability to translate it to Hungarian

### ISSUE THREAD

**Issue by KristofKekesi** [yaichenbaum/Quick-Pad#442]
Please generate the files I recuire to translate Quick-Pad to Hungarian.

**Comment by yaichenbaum** [comment]
@KristofKekesi Is that hu-HU?

**Comment by KristofKekesi** [comment]
yes

**Comment by yaichenbaum** [comment]
@KristofKekesi I added hu-HU to the `master` branch.
