### ISSUE TITLE
Part of the interface language display error, display is not simplified Chinese

### ISSUE THREAD

**Issue by Gaoyifei1011** [yaichenbaum/Quick-Pad#448]
Part of a display error under the three menu, not simplified Chinese.
![image](https://user-images.githubusercontent.com/49179966/103459906-36ac1580-4d4d-11eb-8b92-95a7936bab9a.png)
Expression icon shown below is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103459906-36ac1580-4d4d-11eb-8b92-95a7936bab9a.png)
Picture in picture mode button shows not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103459929-56dbd480-4d4d-11eb-8a87-c9e8bb71c5fb.png)
The regular menu display not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103459952-825ebf00-4d4d-11eb-8d04-49ab0b091ab0.png)
Topic selection part of a display is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103459976-acb07c80-4d4d-11eb-8822-857c62fcd6f3.png)
Font Settings is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103459991-cf429580-4d4d-11eb-9f7e-2ae4080e390d.png)
Advanced Settings is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103460004-e97c7380-4d4d-11eb-89c9-9708237288fe.png)
About is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103460024-044ee800-4d4e-11eb-9a84-13b0a3465c88.png)
I hope I can in the future within one or two versions can solve the problem of the translation errors, thanks for developers to provide such a good application

**Comment by Gaoyifei1011** [comment]
And search is not simplified Chinese
![image](https://user-images.githubusercontent.com/49179966/103460054-44ae6600-4d4e-11eb-8932-6d19a6fe1d28.png)

**Comment by yaichenbaum** [comment]
@Gaoyifei1011 This is because the translations are a little out of date, would you like to update the translations?

**Comment by Gaoyifei1011** [comment]
About the translation was, indeed, some out of date, and the translation would not be simplified Chinese, but other languages, want to ask the developer didn't check out the mistakes？

**Comment by yaichenbaum** [comment]
@Gaoyifei1011 This issue should be resolved with #459.
