### ISSUE TITLE
Add ability to search selected text with DuckDuckGo

### ISSUE THREAD

**Issue by rafal06** [yaichenbaum/Quick-Pad#452]
# **Is your feature request related to a problem? Please describe.**

I like ability to search selected text from context menu, but I prefer DuckDuckGo search engine.

# **Describe the solution you'd like**

Add a buton to search selected text with DuckDuckGo.

# **Describe alternatives you've considered**

Adding ability to set default search engine in settings and adding option in context menu to search with default search engine instead of separate buttons for Google, Bing, etc.

# **Additional context**

![buttons for Google and Bing](https://user-images.githubusercontent.com/70489677/105379479-27620e80-5c0d-11eb-9dbb-9d75b8d8b9a8.png)

**Comment by Jlll1** [comment]
I'd lke to work on this. But I think the best solution would be to use the default search engine.

**Comment by yaichenbaum** [comment]
> I'd lke to work on this. But I think the best solution would be to use the default search engine.

Searching with the default search engine would be ideal.

**Comment by yaichenbaum** [comment]
I don't have any plans to implement this change.
