### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by ataberkcemunal** [yaichenbaum/Quick-Pad#460]
How to download the app with the source code? I build the .sln file but "QuickPad.UI.exe" does not open.

**Comment by yaichenbaum** [comment]
@ataberkcemunal Did you build the UWP project?

**Comment by ataberkcemunal** [comment]
Sorry I cannot understand, I am new at coding. Can you just tell me how to download the app with the source code?

**Comment by yaichenbaum** [comment]
@ataberkcemunal Do you have the solution open in Visual Studio?

**Comment by ataberkcemunal** [comment]
Yes. After I open the solution in Visual Studio and build it, I am trying to open the "QuickPad.UI.exe" but it does not open.

**Comment by yaichenbaum** [comment]
@ataberkcemunal UWP applications work differently and you aren't meant to run the exe file. Does it work to open Quick Pad from the start menu?

**Comment by ataberkcemunal** [comment]
I did not download it from the Microsoft Store so there is nothing in the start menu. Can't I download the app with the source codes?

**Comment by yaichenbaum** [comment]
@ataberkcemunal Can you right click on the QuickPad.UI project in solution explorer and click on "Set as startup project"?
