### ISSUE TITLE
Weird behavior when scroll zooming

### ISSUE THREAD

**Issue by Leisvan** [yaichenbaum/Quick-Pad#462]
When you use Ctrl + Mouse scroll the behavior feels quite weird. What you'd expect is a font size increase or a zoom on the entire content on the control. What happens is kind of a weird zoom with rendering flashes and the scrollbar adds new space to scroll to. 
I'm not familiar with how this works internally, maybe I'm losing something here, but it certainly feels weird.

The other part is that, if it zooms in and out, there's no indicator on the current zoom state, which makes things even more confusing.

Hope this helps, keep the good work 💪.

**Comment by yaichenbaum** [comment]
@Leisvan Can you share a screen recording of the flashes? Quick Pad uses the standard scroll viewer and it looks like it's working correctly.

**Comment by Leisvan** [comment]
Probably it is a system problem (UWP). When I zoom in it flashes a little bit, when I zoom out it behaves as expected.

**Comment by yaichenbaum** [comment]
@Leisvan that's probably the case, keeping this in mind, I'm going to close this issue for now.
