### ISSUE TITLE
More information on the 'About' section

### ISSUE THREAD

**Issue by Leisvan** [yaichenbaum/Quick-Pad#463]
It would be really nice if the app had more information on the About section, like a GitHub link or a 'What's new' section. This may seem trivial, but sometimes even I get lose myself finding the app on GitHub, and the most enthusiastic users like to see what the app has in its latest updates after some time losing track of that.

Hope this helps.

**Comment by Leisvan** [comment]
Sorry for the bug tag, can you tag this as feature request? Thanks 😁

**Comment by yaichenbaum** [comment]
@Leisvan I added a link to the release notes.
