### ISSUE TITLE
German translation is not working

### ISSUE THREAD

**Issue by SirKubiac** [yaichenbaum/Quick-Pad#465]
**Describe the bug**
If german language is selected in settings, the app shows spanish translation.

**To Reproduce**
1. Open settings
2. change language to Deutsch
3. restart app

**Expected behavior**
All elements should be translated in german.

**Screenshots**
https://1drv.ms/u/s!AmD3NDEq3qn3ksBkYc7mjYeaR2iDQw?e=k25eU3

**Desktop (please complete the following information):**
- OS Version:  Windows 10 20H2 19042.1023
- App version:  6.2.0.0

**Comment by yaichenbaum** [comment]
@SirKubiac Thank you for the bug report, this issue should be resolved in `main`.
