### ISSUE TITLE
Unable to download app from GitHub.

### ISSUE THREAD

**Issue by AlfarexGuy2019** [yaichenbaum/Quick-Pad#466]
Hello Developers!
I hope you are all safe during the pandemic.
I recently came across this project and I liked the idea very much.
Following the download instructions as per the README.md of the repo, I navigated to the [Releases Tab](https://github.com/yaichenbaum/Quick-Pad/releases) but I couldn't find any application or any further instructions for downloading.
Support would be appreciated.
Regards,
[AlfarexGuy2019](https://github.com/AlfarexGuy2019)

**Comment by yaichenbaum** [comment]
@AlfarexGuy2019 Thank you for opening this issue, the proper way to download Quick Pad is through the [Microsoft Store](https://www.microsoft.com/store/productId/9PDLWQHTLSV3).

**Comment by AlfarexGuy2019** [comment]
Could I please get a free msix installer? I want to test the app. unfortunately, I cannot install Microsoft store apps due to system file corruption. and i am unable to use VS2019 to edit the project.

**Comment by yaichenbaum** [comment]
@AlfarexGuy2019 Sorry, besides for building from the source the only way to download the app is from the Microsoft Store.

**Comment by jayruinsthings** [comment]
the Microsoft Store has been inconsistent the past 2 months of Insider dev builds. it will open in a window but not load, takes random app repairs in between my sacrifices to the Gods for rain, diet mountain dew, and being Microsoft's Beta lul. basically I wish I had a backdoor to update Store apps made by devs ala Android sideload?🤔🤪
