### ISSUE TITLE
Parts of the interface are not Chinese

### ISSUE THREAD

**Issue by Gaoyifei1011** [yaichenbaum/Quick-Pad#467]
Parts of the interface are not translated to Chinese
部分界面没有汉化
编辑菜单的“时间/日期”选项没有汉化
The "time/date" option in the edit menu is not localized
![image](https://user-images.githubusercontent.com/49179966/122784150-cab26f00-d2e4-11eb-857d-9b2d29fa40a0.png)
视图菜单的“返回默认模式”，”覆盖模式“，“Markdown 预览”选项没有汉化
View menu "back to default mode", "overlay mode", "Markdown preview" options are not translated to Chinese
![image](https://user-images.githubusercontent.com/49179966/122784782-5a581d80-d2e5-11eb-9bb7-4097e6999267.png)
缩放选项的子选项“恢复默认缩放”没有汉化
The "restore default zoom" suboption of the zoom option is not localized
![image](https://user-images.githubusercontent.com/49179966/122784952-7fe52700-d2e5-11eb-8144-ad739b7b9ec9.png)
查找框中的标记内容"查找什么?"没有汉化
The tag "Looking for?" in the search box is not  localized
![image](https://user-images.githubusercontent.com/49179966/122785462-feda5f80-d2e5-11eb-8908-d95689b73cf8.png)
表情按钮的“插入Emoji表情”提示没有汉化
The "Insert Emojis" tip on the Emoji button is not translated to Chinese
![image](https://user-images.githubusercontent.com/49179966/122785732-3517df00-d2e6-11eb-8705-cf624be124b2.png)
”紧凑覆盖模式“的提示没有汉化
The prompt for "compact overlay mode" is not localized
![image](https://user-images.githubusercontent.com/49179966/122785957-62648d00-d2e6-11eb-8c01-579cc0c3c0df.png)
更多菜单的经典模式，Markdown预览和退出选项没有汉化
More menus in classic mode, Markdown Preview and Exit options are not translated to Chinese
![image](https://user-images.githubusercontent.com/49179966/122786700-27af2480-d2e7-11eb-92b3-e94eba345365.png)
设置选项的常规设置所标记的内容没有汉化
The content marked by general Settings for Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122786779-3f86a880-d2e7-11eb-8639-e5a5b28510b4.png)
设置选项的主题设置所标记的内容没有汉化
The content marked by theme Settings for Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122787025-7f4d9000-d2e7-11eb-9ab5-2db122be54d9.png)
![image](https://user-images.githubusercontent.com/49179966/122787130-9ab89b00-d2e7-11eb-8c6a-eae85b96c55c.png)
设置选项的字体设置所标记的内容没有汉化
The content marked by font Settings for Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122787242-b6bc3c80-d2e7-11eb-90d4-6ab504983145.png)
设置选项的高级设置所标记的内容没有汉化
The content marked by the advanced Settings of the Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122787464-f08d4300-d2e7-11eb-90ff-7d56a9f127b2.png)
设置选项的"关于 Quick Pad"提示没有汉化
The "About Quick Pad" prompt for Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122787663-22060e80-d2e8-11eb-8320-20b1c6d35a22.png)
设置选项的"关于 Quick Pad"所标记的内容没有汉化
The content marked by the ”About Quick Pad“ of the Settings options is not localized
![image](https://user-images.githubusercontent.com/49179966/122787795-43ff9100-d2e8-11eb-9cd7-3af9e08c43a0.png)
希望能够在下一个版本可以解决完这些汉化问题，谢谢开发者的辛勤付出
Hope to be able to solve these problems in the next version of the localization, thank the developers for their hard work

**Comment by yaichenbaum** [comment]
@Gaoyifei1011 would you like to update the translations?
