### ISSUE TITLE
Download Issues. Requesting a *.msixbundle Installer

### ISSUE THREAD

**Issue by AlfarexGuy2019** [yaichenbaum/Quick-Pad#468]
@yaichenbaum Could I please get a free msix installer? I want to test the app. unfortunately, I cannot install Microsoft store apps due to system file corruption. and i am unable to use VS2019 to edit the project.

**Comment by yaichenbaum** [comment]
@AlfarexGuy2019 Sorry, besides for building from the source the only way to download the app is from the Microsoft Store.

**Comment by AlfarexGuy2019** [comment]
okay. Thanks.
