### ISSUE TITLE
The theme color has changed

### ISSUE THREAD

**Issue by zepidan** [yaichenbaum/Quick-Pad#474]
**Is your feature request related to a problem? Please describe.**
 when I opened it today the color of cobalt theme had changed to navy (although it still says cobalt) and the only reason I bought the program was so that I can use the cobalt theme. 

**Describe the solution you'd like**
bring the old cobalt color back. 

**Describe alternatives you've considered**

**Additional context**

**Comment by yaichenbaum** [comment]
@zepidan the cobalt theme is the same value as before, the difference is that it's using mica instead of acrylic.

**Comment by zepidan** [comment]
So when you click on the settings icon a lighter colored window to the main color pops up and that was the previous cobalt color I believe. I used the color picker on it and it says #0047AB (cobalt) and #114389? The colors now (and your example above) I feel are closer to navy/indigo. I would love to have the cobalt color back if possible... I really loved typing on it and now it's just gone. (I understand if it's hard to bring it back- I panicked and changed the theme on my ++notepad settings to cobalt (previously it was set to black with neon green à la matrix) but that program isn't as clean looking as the quick pad.
![5628dfcf042248f1a9d99c0fd1a2ea5a](https://user-images.githubusercontent.com/91402207/134794350-7e042387-324d-46fa-893f-0acdb2c7cd8d.jpg)

**Comment by yaichenbaum** [comment]
@zepidan the value is the same as before, there opacity change may have something to do with it. I'll continue playing around to see if I can improve the theme.

**Comment by zepidan** [comment]
So it's translucent and is being affected by a darker color? It's not my PC's personalization set to dark theme affecting it right? I did test different settings and it doesn't seem to matter. 
![cobalt theme](https://user-images.githubusercontent.com/91402207/134794928-c80368dc-75f1-4d9f-9575-7640ad7493e2.JPG)
. 
thank you!

**Comment by yaichenbaum** [comment]
@zepidan correct, it's a change I made to the opacity to enable mica to work.
