### ISSUE TITLE
File Association?

### ISSUE THREAD

**Issue by SilverMarcs** [yaichenbaum/Quick-Pad#479]
The "open with" dialog doesnt display quickpad, although opening file from inside the app works just fine.
Is this intended behaviour? 

PS. I've compiled from github, its not the MS Store version.

**Comment by yaichenbaum** [comment]
@SilverMarcs it should work fine even for the debug build, this sounds like an issue with Windows, can you report it in the Feedback Hub?

**Comment by SilverMarcs** [comment]
> @SilverMarcs it should work fine even for the debug build, this sounds like an issue with Windows, can you report it in the Feedback Hub?

Ill do that. Meanwhile, do you know how to manually select app to open with? As in where is quickpad installed when installed externally?

**Comment by yaichenbaum** [comment]
It's installed in `C:\Program Files\WindowsApps`.

**Comment by SilverMarcs** [comment]
I should mention that file association does work with common text files. But for something like .srt, it doesnt appear in the open with dialog. But opening from inside the app works. I cannot tell for other fil types at the moment

**Comment by yaichenbaum** [comment]
> I should mention that file association does work with common text files. But for something like .srt, it doesnt appear in the open with dialog. But opening from inside the app works. I cannot tell for other fil types at the moment

That would explain it, it shouldn't be too hard to add it to the list of supported file types in the manifest, do you want to open a PR?

**Comment by SilverMarcs** [comment]
> > I should mention that file association does work with common text files. But for something like .srt, it doesnt appear in the open with dialog. But opening from inside the app works. I cannot tell for other fil types at the moment
> 
> That would explain it, it shouldn't be too hard to add it to the list of supported file types in the manifest, do you want to open a PR?

Woops dont know how any of that works

**Comment by yaichenbaum** [comment]
@SilverMarcs there is a manifest file with a list of supported file types, I'll try to include this in the next update.
